baseURL = "https://radarsymphony.github.io/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Krypton Code"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/avatar.jpg"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-l"

  # Description to display on homepage
  description = "A DevOps story"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#fe0002"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo", "devops", "tech", "documentation"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  #showPostsOnHomePage = ""

  # Footer text
  footer = "Krypton Code"

  socialIcons = [
      {name = "github", url = "https://github.com/radarsymphony"},
    ]

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/radarsymphony"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"
